{"event": "verbose", "uuid": "33e48945-b182-4cf9-b0b6-f9aff2039995", "counter": 3, "stdout": "\u001b[0;31mThe error appears to be in '/home/vescana/test_ansible_molecule/roles/web_servers/tasks/main.yml': line 4, column 3, but may\u001b[0m", "start_line": 2, "end_line": 3, "runner_ident": "591aefc3-e227-407a-8180-2c8dd28d5dbb", "created": "2022-04-11T16:25:22.649335"}