{"event": "verbose", "uuid": "e02bfdae-0602-4c33-a5bf-3c90ed0c7e9d", "counter": 3, "stdout": "\u001b[0;31mThe error appears to be in '/home/vescana/test_ansible_molecule/playbooks/site.yml': line 24, column 7, but may\u001b[0m", "start_line": 2, "end_line": 3, "runner_ident": "0bb81b08-4689-4cd0-8426-151c11cfd37d", "created": "2022-04-19T15:04:10.932436"}