{"event": "verbose", "uuid": "638f484b-7e63-440c-93c3-866b84950b7f", "counter": 3, "stdout": "\u001b[0;31mThe error appears to be in '/home/vescana/test_ansible_molecule/roles/web_servers/tasks/main.yml': line 4, column 3, but may\u001b[0m", "start_line": 2, "end_line": 3, "runner_ident": "d5497373-285a-40da-8f09-7549771bbae2", "created": "2022-04-11T16:01:06.310612"}