{"event": "verbose", "uuid": "6b58307a-585e-4455-95e0-1e6b4107f6c7", "counter": 3, "stdout": "\u001b[0;31mThe error appears to be in '/home/vescana/test_ansible_molecule/roles/web_servers/tasks/main.yml': line 2, column 3, but may\u001b[0m", "start_line": 2, "end_line": 3, "runner_ident": "8c4143cb-3242-4329-a2ec-5469507e3ca1", "created": "2022-04-11T16:17:30.501329"}