{"event": "verbose", "uuid": "6204cba0-30d4-4c7b-bca2-87a0b0814be5", "counter": 3, "stdout": "\u001b[0;31mThe error appears to be in '/home/vescana/test_ansible_molecule/roles/web_servers/tasks/main.yml': line 4, column 3, but may\u001b[0m", "start_line": 2, "end_line": 3, "runner_ident": "ec3268e9-c837-4739-aa25-1fd08a2afef5", "created": "2022-04-11T16:06:12.367112"}